// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeMql480VGXjCXQH-dFOAg3JrCkkITO1Q',
    appId: '1:944882437880:web:6643ef5ac094e96b17f50d',
    messagingSenderId: '944882437880',
    projectId: 'rent-car-backend-app',
    authDomain: 'rent-car-backend-app.firebaseapp.com',
    storageBucket: 'rent-car-backend-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf_760R2sPNtHQpaUNug3U2ts5cu2Mqww',
    appId: '1:944882437880:android:7b346d4bfd780ba217f50d',
    messagingSenderId: '944882437880',
    projectId: 'rent-car-backend-app',
    storageBucket: 'rent-car-backend-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiNVlUsAu-BOU7Mnb0OZLLfHpvDDtqZ0Q',
    appId: '1:944882437880:ios:62dcdde3c577e8d217f50d',
    messagingSenderId: '944882437880',
    projectId: 'rent-car-backend-app',
    storageBucket: 'rent-car-backend-app.firebasestorage.app',
    iosBundleId: 'com.example.carRentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiNVlUsAu-BOU7Mnb0OZLLfHpvDDtqZ0Q',
    appId: '1:944882437880:ios:62dcdde3c577e8d217f50d',
    messagingSenderId: '944882437880',
    projectId: 'rent-car-backend-app',
    storageBucket: 'rent-car-backend-app.firebasestorage.app',
    iosBundleId: 'com.example.carRentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeMql480VGXjCXQH-dFOAg3JrCkkITO1Q',
    appId: '1:944882437880:web:cbd69783ab14e8d917f50d',
    messagingSenderId: '944882437880',
    projectId: 'rent-car-backend-app',
    authDomain: 'rent-car-backend-app.firebaseapp.com',
    storageBucket: 'rent-car-backend-app.firebasestorage.app',
  );
}
